name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag standaml:${{github.sha}}

    - name: Build
      run: docker run --user root --rm -w /src --mount type=bind,src=$(pwd),dst=/src standaml:${{github.sha}} sh -c "cd src/ && make build"
    
    - name: Test
      run: docker run --user root --rm -w /src --mount type=bind,src=$(pwd),dst=/src standaml:${{github.sha}} sh -c "cd src/ && make test"
