name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag standaml:$(date +%s)

    - name: Build
      run: docker run --rm -w /src --mount type=bind,src=$(pwd),dst=/src standaml:$(date +%s) sh -c "cd src/ && make build"
    
    - name: Test
      run: docker run --rm -w /src --mount type=bind,src=$(pwd),dst=/src standaml:$(date +%s) sh -c "cd src/ && make test"
